CREATE TABLE Paciente(
	IdPaciente SERIAL NOT NULL PRIMARY KEY UNIQUE,
	Nome_Paciente VARCHAR(50) NOT NULL,
	Data_Nascimento_Paciente VARCHAR(10) NOT NULL, 
	Cpf VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE Consulta(
	IdConsulta SERIAL NOT NULL PRIMARY KEY UNIQUE,
	IdMedico NOT NULL UNIQUE,
	Nome_medico VARCHAR(50) NOT NULL,
	Data_Nascimento_Paciente VARCHAR(10) NOT NULL, 
	Cpf VARCHAR(14) NOT NULL UNIQUE
);

